/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StoreRouteImport } from './routes/store'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IpIdRouteImport } from './routes/ip.$id'
import { Route as CreatorSlugRouteImport } from './routes/creator.$slug'
import { Route as ContentIdRouteImport } from './routes/content.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpIdRoute = IpIdRouteImport.update({
  id: '/ip/$id',
  path: '/ip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSlugRoute = CreatorSlugRouteImport.update({
  id: '/creator/$slug',
  path: '/creator/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/portfolio': typeof PortfolioRoute
  '/store': typeof StoreRoute
  '/upload': typeof UploadRoute
  '/content/$id': typeof ContentIdRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/ip/$id': typeof IpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/portfolio': typeof PortfolioRoute
  '/store': typeof StoreRoute
  '/upload': typeof UploadRoute
  '/content/$id': typeof ContentIdRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/ip/$id': typeof IpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/marketplace': typeof MarketplaceRoute
  '/portfolio': typeof PortfolioRoute
  '/store': typeof StoreRoute
  '/upload': typeof UploadRoute
  '/content/$id': typeof ContentIdRoute
  '/creator/$slug': typeof CreatorSlugRoute
  '/ip/$id': typeof IpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/marketplace'
    | '/portfolio'
    | '/store'
    | '/upload'
    | '/content/$id'
    | '/creator/$slug'
    | '/ip/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/marketplace'
    | '/portfolio'
    | '/store'
    | '/upload'
    | '/content/$id'
    | '/creator/$slug'
    | '/ip/$id'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/marketplace'
    | '/portfolio'
    | '/store'
    | '/upload'
    | '/content/$id'
    | '/creator/$slug'
    | '/ip/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PortfolioRoute: typeof PortfolioRoute
  StoreRoute: typeof StoreRoute
  UploadRoute: typeof UploadRoute
  ContentIdRoute: typeof ContentIdRoute
  CreatorSlugRoute: typeof CreatorSlugRoute
  IpIdRoute: typeof IpIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip/$id': {
      id: '/ip/$id'
      path: '/ip/$id'
      fullPath: '/ip/$id'
      preLoaderRoute: typeof IpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$slug': {
      id: '/creator/$slug'
      path: '/creator/$slug'
      fullPath: '/creator/$slug'
      preLoaderRoute: typeof CreatorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  MarketplaceRoute: MarketplaceRoute,
  PortfolioRoute: PortfolioRoute,
  StoreRoute: StoreRoute,
  UploadRoute: UploadRoute,
  ContentIdRoute: ContentIdRoute,
  CreatorSlugRoute: CreatorSlugRoute,
  IpIdRoute: IpIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
